import type { Metadata } from 'next';
import MainLayout from '@/shared/components/layout/main-layout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainLayout children={children} />
  );
}
