import { convertDatesToServerTime } from "@/shared/helpers/time";
import { group } from "console";

const PATCH_1_0 = [
    {
        name: "Alloy Smelt Limited Time Battle Event",
        img: "https://aki-gm-resources-back.aki-game.net/notice/image/WSrKcdNwytNiSRAs.jpg",
        color: "#282840",
        startDate: "2024-06-06 10:00",
        endDate: "2024-06-27 03:59",
    },
    {
        name: "Wuthering Exploration Limited-Time Event",
        img: "https://aki-gm-resources-back.aki-game.net/notice/image/uMJRhEmCgPNElAxX.jpg",
        color: "#1E1D21",
        startDate: "2024-06-13 10:00",
        endDate: "2024-06-27 03:59",
    },
    {
        name: "Second Coming of Solaris Limited Time Collection Event",
        img: "https://aki-gm-resources-back.aki-game.net/notice/image/jpGLPKjxPaIfhrbw.jpg",
        color: "#191D1F",
        startDate: "2024-06-13 04:00",
        endDate: "2024-06-27 03:59",
    },
    {
        name: '"Chord Cleansing" LT Echo Double Drop Event',
        img: "https://aki-gm-resources-back.aki-game.net/notice/image/VLUKnFABIwENgpiX.jpg",
        color: "#191D1F",
        startDate: "2024-06-20 04:00",
        endDate: "2024-06-27 03:59",
    },
];

const PATCH_1_1 = [
    {
        name: "Traces of Mt. Firmament",
        desc: "Photo Collection Event",
        img: "https://snipboard.io/VA7tnJ.jpg",
        color: "#7a4738",
        description:
            "Follow the clues to explore the corresponding area, take the correct photos, or search at the target location. Completing the above tasks will grant rewards.",
        startDate: "2024-06-28 12:00",
        endDate: "2024-08-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Gifts of Celestial Light: 7-day Login Event",
        img: "https://snipboard.io/ET3clt.jpg",
        description:
            "Log into the game and check in to claim rewards: 5x Radiant Tide & 5x Lustrous Tide",
        color: "#4f493e",
        startDate: "2024-06-28 12:00",
        endDate: "2024-08-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Limited Time Check-in Event",
        img: "https://snipboard.io/cPrHtu.jpg",
        color: "#af6d69",
        description:
            "Log in the game and check in to receive corresponding rewards on respective dates.",
        startDate: "2024-07-04 04:00",
        endDate: "2024-08-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Bountiful Crescendo",
        desc: "Leveling Material Double Drop Event",
        img: "https://snipboard.io/Ngs67D.jpg",
        color: "#7a768d",
        description:
            "Consume Wavesplates to claim double rewards when completing [Simulation Challenge] and [Forgery Challenge].",
        startDate: "2024-07-11 04:00",
        endDate: "2024-07-18 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Tactical Simulacra: Limited-time Battle Challenge",
        img: "https://snipboard.io/sX1Mva.jpg",
        color: "#89848c",
        description:
            "Enter a special Simulation Challenge where you'll be powered up with special buffs to challenge formidable enemies. Accumulate points to unlock valuable rewards! Rewards: 500x Astrite, 1x Malleable Elite Class Echo I, 1x Malleable Elite Class Echo II, Premium Tuners.",
        startDate: "2024-07-20 10:00",
        endDate: "2024-08-08 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Lollo Campaign: Limited-time Commission Event",
        img: "https://snipboard.io/ey1GD8.jpg",
        color: "#8f7f68",
        description:
            "Complete tasks in [Lollo Campaign] to earn Lollo Stamps. Lollo Stamps can be used in the roulette of 'Lollo Helper' to get random rewards.",
        startDate: "2024-07-25 10:00",
        endDate: "2024-08-08 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Chord Cleansing",
        desc: "Echo Double Drop Event",
        img: "https://snipboard.io/7lzZ6x.jpg",
        color: "#1d3d50",
        description:
            "Consume Wavesplates to claim double rewards when completing the [Tacet Suppression] challenge.",
        startDate: "2024-08-06 04:00",
        endDate: "2024-08-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
];

const PATCH_1_2 = [
    {
        name: "By Moon's Grace",
        img: "https://snipboard.io/VWCEnw.jpg",
        description: `Assist in the preparation for the Moonlit Fair with Xiangli Yao. The Popularity of the Moon-Chasing Festival can be earned by building "Fair Stalls" and completing "Wishes". You may invite Resonators as your Companions by completing Side Quests during the preparation.`,
        startDate: "2024-08-15 13:00",
        endDate: "2024-09-28 15:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        isGlobal: true,
        color: "#e4b087",
    },
    {
        name: "Gifts of Lunar Radiance: 7-day Sign-in Event",
        img: "https://snipboard.io/4w9vZM.jpg",
        description:
            "Log into the game and check into claim rewards: 5*Radiant Tide and 5*Lustrous Tide.",
        endDate: "2024-09-28 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        startDate: "2024-08-15 13:00",
        isGlobal: true,
        color: "#a1ccfa",
    },
    {
        name: "Bountiful Crescendo: Leveling Material Double Drop Event",
        img: "https://snipboard.io/SwirLt.jpg",
        description: `Consume Waveplates to claim double rewards when completing the "Simulation Challenge" and "Forgery Challenge".`,
        startDate: "2024-08-29 04:00",
        endDate: "2024-09-05 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        color: "#2a3043",
    },
    {
        name: "Do Echoids Dream of Electric Sheep? Limited-time Defense Event",
        img: "https://snipboard.io/6cGFbt.jpg",
        description: `Enter a special simulation domain and protect the devices from Tacet Discords' attacks until they're eliminated. During the test, Cosmos will provide Echoids to significantly boost Resonators' combat power. Rewards; 500*Astrite, Malleable Elite Class Echo I, Malleable Elite Class Echo II, Premium Sealed Tube, Shell Credits.`,
        startDate: "2024-09-05 10:00",
        endDate: "2024-09-26 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        color: "#7a8289",
    },
    {
        name: "Converging Paths",
        img: "https://snipboard.io/KomyFi.jpg",
        description: `Participate in the "By Moon's Grace" event and prepare for the Moonlit Fair. Upon reaching the specific Popularity, the 5-star Resonator Xiangli Yao can be claimed for free!`,
        startDate: "2024-09-07 10:00",
        endDate: "2024-09-28 15:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        color: "#323b61",
    },
    {
        name: "Alloy Smelt II: Limited-time Defense Event",
        img: "https://snipboard.io/5F7Ha3.jpg",
        description: `Head to a special Sonoro Sphere where you'll be able to release your battle strength with diverse team compositions and corresponding buffs. Rewards; 500*Astrite, Malleable Elite Class Echo I, Malleable Elite Class Echo II, Premium Resonance Potions, Premium Energy Cores.`,
        startDate: "2024-09-16 10:00",
        endDate: "2024-09-28 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        color: "#181c30",
    },

    {
        name: "Chord Cleansing: Echo Double Drop Event",
        img: "https://snipboard.io/SwirLt.jpg",
        description: `Consume Waveplates to claim double rewards when completing the "Tacet Suppression" challenge.`,
        startDate: "2024-09-20 04:00",
        endDate: "2024-09-27 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        reliability: "Official",
        color: "#2a3043",
    },
];

const PATCH_1_3 = [
    {
        name: "The Black Shores - Regional Events",
        img: "https://snipboard.io/iYWCPA.jpg",
        description: `Participate in "Where Stars Slumber - Area Exploration Event" and "Amidst the Stars - Photo Collection Event" to get rewards; 740*Astrite, 1*Deep Sky Blazar Weapon Chest, Forgery Premium Supply, Molded Elite Class Echo I, Molded Elite Class Echo II.`,
        startDate: "2024-09-29 11:00",
        endDate: "2024-11-13 15:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#34356f",
        group: 1,
    },
    {
        name: "Parade of Stars - Special Leveling Event",
        img: "https://snipboard.io/2qypKM.jpg",
        description: `Complete 4 themed leveling activities Resonator, weapon, Echo, and skill to earn rewards based on materials consumed. Rewards; 50*Premium Sealed Tube, 50*Premium Resonance Potion, 34*Premium Energy Core, 25*Forgery Premium Supply, 28*Premium Enclosure Tank.`,
        startDate: "2024-09-29 11:00",
        endDate: "2024-11-13 15:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#121926",
        group: 2,
    },
    {
        name: "Gifts of Sea Breeze: 7-day Sign-in Event",
        img: "https://snipboard.io/HNjqi0.jpg",
        description:
            "Log into the game and check into claim rewards: 5*Radiant Tide and 5*Lustrous Tide.",
        startDate: "2024-09-29 11:00",
        endDate: "2024-11-13 03:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#72809e",
        group: 3,
    },
    {
        name: "Fairy Tale's Finale - Featured Co-op Combat Event",
        img: "https://snipboard.io/6ptCEy.jpg",
        description: `Fairy Tale's Finale offers 12 event stages that will unlock one by one. Choose "Dorothy's Companions" as Echoes to assist you in battle, which greatly enhances the combat abilities of Resonators. Rewards; 600*Astrite, Forgery Premium Supply, Premium Sealed Tube, Premium Energy Core, Premium Tuner.`,
        startDate: "2024-10-01 10:00",
        endDate: "2024-10-24 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#c6afbb",
        group: 4,
    },
    {
        name: "Wuthering Exploration - Featured Exploration Event",
        img: "https://snipboard.io/Wo1MBS.jpg",
        description: `Complete Survey Tasks and accumulate Survey Points to secure valuable rewards offered by the Pioneer Association. Rewards; 2000000*Shell Credit, 30*Tailored Ring, 30*FF Whisperin Core, 30*FF Howler Core.`,
        startDate: "2024-10-10 10:00",
        endDate: "2024-10-24 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#405dab",
        group: 5,
    },
    {
        name: "Solaris Weather Forecast - Featured Platforming Event",
        img: "https://snipboard.io/dFa1nR.jpg",
        description: `As time progress, new Detection Points will unlock. Head to the Detection Points to begin combat challenges. Use secondary mechanisms nearby to collect Surveillance Datasets before time runs out. Rewards; 400*Astrite, Premium Resonance Potion, Premium Energy Core, Premium Sealed Tube, Forged Advanced Supply.`,
        startDate: "2024-10-10 10:00",
        endDate: "2024-10-31 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#35546a",
        group: 6,
    },
    {
        name: "Bountiful Crescendo: Leveling Material Double Drop Event",
        img: "https://snipboard.io/4i3kVO.jpg",
        description: `Consume Waveplates to claim double rewards when completing the "Simulation Challenge" and "Forgery Challenge".`,
        startDate: "2024-10-17 04:00",
        endDate: "2024-10-24 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        group: 7,
    },
    {
        name: "Infinite Battle Simulation - Featured Arena Combat Event",
        img: "https://snipboard.io/j68R2V.jpg",
        description: `Defeat as many enemies as possible and open Supply Chests to claim Tactic Points and Low-Capacity Variable buffs. Rewards; 600*Astrite, Malleable Elite Class Echo I, Malleable Elite Class Echo II, Premium Sealed Tube, Shell Credit.`,
        startDate: "2024-10-24 10:00",
        endDate: "2024-11-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#2f4887",
        group: 4,
    },
    {
        name: "Lollo Compaign: Rerun - Featured Commission Event",
        img: "https://snipboard.io/hKnQ7i.jpg",
        description: `Complete Lollo Campaigns once per day to obtain a set number of Lotto Stamps. Exchange these stamps for a special delivery from Lollo Helper, granting you one spin on the wheel lottery. Rewards; 400*Astrite, 5*Lustrous Tide, Forgery Premium Supply, Premium Sealed Tube, Crystal Solvent.`,
        startDate: "2024-10-24 10:00",
        endDate: "2024-11-07 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#755b3f",
        group: 5,
    },
    {
        name: "Wuthering Exploration - Mt. Firmament Featured Exploration Event",
        img: "https://snipboard.io/W9kgXx.jpg",
        description: `Complete Survey Tasks and accumulate Survey Points to secure valuable rewards offered by the Pioneer Association. Rewards; 800*Astrite, 1*Malleable Elite Class Echo I, 1*Malleable Elite Class Echo II, 100*Premium Tuner, 30*Premium Sealed Tube.`,
        startDate: "2024-10-31 10:00",
        endDate: "2024-11-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        color: "#a9bcd2",
        group: 6,
    },
    {
        name: "Chord Cleansing: Echo Double Drop Event",
        img: "https://snipboard.io/uDQv0C.jpg",
        description: `Consume Waveplates to claim double rewards when completing the "Tacet Suppression" challenge.`,
        startDate: "2024-11-06 04:00",
        endDate: "2024-11-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
        reliability: "Official",
        group: 7,
    },
];

const PATCH_1_4 = [
    {
        name: "Gifts of Fleeting Dreams: 7-day Sign-in Event",
        img: "https://snipboard.io/cLjW6G.jpg",
        description:
            "Log into the game and check into claim rewards: 5*Radiant Tide and 5*Lustrous Tide.",
        startDate: "2024-11-14 11:00",
        endDate: "2025-01-01 03:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#cb7796",
        reliability: "Official",
        group: 1,
    },
    {
        name: "Somnium Labyrinth - Somnoire Adventure Event",
        img: "https://snipboard.io/NLukHF.jpg",
        description: `This event includes 3 sub-events: Dreamscape Odyssey, Rift Runner, and Nightmare Revisits. Rescue your Resonator companions from their Dreamscapes. Limited Rewards; 800*Astrite, 1*Somnoire Anchor, 1*Projection: Somniore Anchor, 4*Hearty Supper, Forgery Premium Supply.`,
        startDate: "2024-11-14 11:00",
        endDate: "2025-01-01 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#5232a2",
        reliability: "Official",
        group: 2,
    },
    {
        name: "Pincer Maneuver Warriors I - Recurring Combat Event",
        img: "https://snipboard.io/tzHkDU.jpg",
        description: `In Pincer Maneuver Warriors, challenge waves of powerful enemies by controlling two teams with special buffs across two separate simulated battlefields.`,
        startDate: "2024-11-14 11:00",
        endDate: "2024-12-12 09:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#768c9a",
        reliability: "Official",
        group: 3,
    },
    {
        name: "Beyond the Waves - Featured Exploration Event",
        img: "https://snipboard.io/2EorCx.jpg",
        description: `During the event, complete event objectives once per day to obtain a set number of Adventure Logs. Each Adventure Log can be exchanged for a random Adventure Package.`,
        startDate: "2024-11-21 10:00",
        endDate: "2024-12-05 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#815b42",
        reliability: "Official",
        group: 4,
    },
    {
        name: "Chord Cleansing: Echo Double Drop Event",
        img: "https://snipboard.io/zu2vQP.jpg",
        description: `Consume Waveplates to claim double rewards when completing the "Tacet Suppression" challenge.`,
        startDate: "2024-12-05 04:00",
        endDate: "2024-12-12 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
        color: "#3e3439",
        group: 4,
    },
    {
        name: "Ragunna Sales Blitz! - Pioneer Association Event",
        img: "https://snipboard.io/CfLJT9.jpg",
        description: `Alannah will be releasing a new investigation quest each day. Complete the surveys to earn corresponding rewards and have a glimpse into the world of Rinascita!`,
        startDate: "2024-12-12 10:00",
        endDate: "2025-01-01 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#3b477d",
        reliability: "Official",
        group: 3,
    },
    {
        name: "Pincer Maneuver Warriors II - Recurring Combat Event",
        img: "https://snipboard.io/tzHkDU.jpg",
        description: `In Pincer Maneuver Warriors, challenge waves of powerful enemies by controlling two teams with special buffs across two separate simulated battlefields.`,
        startDate: "2024-12-12 10:00",
        endDate: "2025-01-01 11:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#456073",
        reliability: "Official",
        group: 4,
    },
    {
        name: "Tactical Simulacra II - Featured Combat Event",
        img: "https://snipboard.io/1puvlO.jpg",
        description: `In Tactical Simulacra II, challenge waves of powerful enemies by using special buffs across different simulation domains.`,
        startDate: "2024-12-19 10:00",
        endDate: "2025-01-01 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#84493b",
        reliability: "Official",
        group: 5,
    },
    {
        name: "Bountiful Crescendo: Material Double Drop Event",
        img: "https://snipboard.io/BwOPmb.jpg",
        description: `Consume Waveplates to claim double rewards when completing a "Simulation" or "Forgery Challenge".`,
        startDate: "2024-12-25 04:00",
        endDate: "2025-01-01 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
        color: "#4f4a49",
        group: 6,
    },
];

const PATCH_2_0 = [
    {
        name: "Gifts of Joyous Tunes: 7-day Sign-in Event",
        img: "https://snipboard.io/s2cjz5.jpg",
        description:
            "Log into the game and check into claim rewards: 5*Radiant Tide and 5*Lustrous Tide.",
        startDate: "2025-01-02 04:00",
        endDate: "2025-02-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#772d32",
        group: 1,
    },
    {
        name: "Grand Opening of the Carnevale: A Welcome Gift from Rinascita",
        img: "https://snipboard.io/0BYSQa.jpg",
        description: `Claim rewards via in-game mail; 10* Radiant Tide, 10* Crystal Solvent.`,
        startDate: "2025-01-02 04:00",
        endDate: "2025-02-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#db7d57",
        group: 2,
    },
    {
        name: "Rinascita: Regional Events",
        img: "https://snipboard.io/7crmLh.jpg",
        description: `Rewards Overview; 770*Astrite, 1*Sigil (Memories about the Isles), Forgery Premium Supply, Premium Sealed Tube, Cyrstal Solvent.`,
        startDate: "2025-01-02 04:00",
        endDate: "2025-02-12 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#ad8384",
        group: 3,
    },
    {
        name: "Pincer Maneuver Warriors III - Recurring Combat Event",
        img: "https://snipboard.io/tzHkDU.jpg",
        description: `In Pincer Maneuver Warriors, challenge waves of powerful enemies by controlling two teams with special buffs across two separate simulated battlefields.`,
        startDate: "2025-01-02 04:00",
        endDate: "2025-01-23 10:00",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#768c9a",
        group: 4,
    },
    {
        name: "Pincer Maneuver Warriors IV - Recurring Combat Event",
        img: "https://snipboard.io/tzHkDU.jpg",
        description: `In Pincer Maneuver Warriors, challenge waves of powerful enemies by controlling two teams with special buffs across two separate simulated battlefields.`,
        startDate: "2025-01-23 10:00",
        endDate: "2025-02-12 11:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#456073",
        group: 4,
    },
    {
        name: "Although Colors Have No Form: Featured Co-op Challenge Event",
        img: "https://snipboard.io/HdjJue.jpg",
        description: `Claudia asks you to investigate the world within the painting and gives you a protective talisman. Within the painted world, the talisman transforms into various Echoes to assist you.`,
        startDate: "2025-01-09 11:00",
        endDate: "2025-01-30 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#486d40",
        group: 5,
    },
    {
        name: "Lollo Campaign: Comeback",
        img: "https://snipboard.io/c2MtWI.jpg",
        description: `During the event, you can complete [Lollo Campaigns] once per day to obtain a set number of Lollo Stamps. Exchange these stamps for a special delivery from Lollo Helper, granting you one spin on the wheel lottery.`,
        startDate: "2025-01-30 10:00",
        endDate: "2025-02-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#97704f",
        group: 5,
    },
    {
        name: "Chord Cleansing: Echo Double Drop Event",
        img: "https://snipboard.io/zu2vQP.jpg",
        description: `Consume Waveplates to claim double rewards when completing the "Tacet Suppression" challenge.`,
        startDate: "2025-01-16 04:00",
        endDate: "2025-01-23 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#3e3439",
        group: 6,
    },
    {
        name: "Dances For Spring's Return: Companion Inivitation Login Event",
        img: "https://snipboard.io/5EswpS.jpg",
        description: `During the event, you can invite one Companion to join you every day. After the invitation, you can claim the corresponding rewards on the event page. Complete all invitations to claim Sanhua's exclusive Outfit, "Exorcistic Adjuration" and other rewards.`,
        startDate: "2025-01-23 10:00",
        endDate: "2025-02-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#aa9d9b",
        group: 6,
    },
    {
        name: "Wuthering Exploration: Nimbus Sanctum",
        img: "https://snipboard.io/PxicsR.jpg",
        description: `Complete Survey Tasks daily to get Survey Points and claim rewards after meeting Survey Point requirements.`,
        startDate: "2025-01-16 10:00",
        endDate: "2025-01-30 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#3a3941",
        group: 7,
    },
    {
        name: "Bountiful Crescendo: Material Double Drop Event",
        img: "https://snipboard.io/BwOPmb.jpg",
        description: `Consume Waveplates to claim double rewards when completing a "Simulation" or "Forgery Challenge".`,
        startDate: "2025-02-06 04:00",
        endDate: "2025-02-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#4f4a49",
        group: 7,
    },
    {
        name: "John Wicktorio: No Debts for Old Men Featured Combat Event",
        img: "https://snipboard.io/c2MtWI.jpg",
        description: `During the event, you will enter a special sphere to battle waves of enemies within a set time limit, with the aid of unique buffs.`,
        startDate: "2025-01-23 11:00",
        endDate: "2025-02-09 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#2c4a63",
        group: 8,
    },
    {
        name: "Celebration Aftertunes: Gratitude for Companionship",
        img: "https://snipboard.io/85dkQc.jpg",
        description: `Claim rewards via in-game mail; 1600* Astrite.`,
        startDate: "2025-01-29 00:00",
        endDate: "2025-02-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1864",
        color: "#4db5e6",
        group: 9,
    },
];

export const ACTIVITIES = [
    // convertDatesToServerTime(PATCH_1_0),
    // convertDatesToServerTime(PATCH_1_1),
    // convertDatesToServerTime(PATCH_1_2),
    // convertDatesToServerTime(PATCH_1_3),
    convertDatesToServerTime(PATCH_1_4),
    convertDatesToServerTime(PATCH_2_0),
];
