import { convertDatesToServerTime } from "@/shared/helpers/time";

const ALL_BANNERS = [
    {
        name: "When Thunder Pours - Yinlin Banner",
        description:
            "During the event, boosted drop rates for 5-star Resonator [Yinlin], 4-star Resonators [Taoqi], [Aalto], and [Yuanwu]!",
        url: "https://wutheringwaves.gg/when-thunder-pours-featured-resonator-convene-boosted-drop-rate-for-yinlin/",
        img: "https://aki-gm-resources-back.aki-game.net/notice/image/XUvRpLaygBSPNnoM.jpg",
        color: "#231C22",
        startDate: "2024-06-06 10:00",
        endDate: "2024-06-26 11:59",
    },
    {
        name: "Absolute Pulsation - Yinlin Weapon Banner",
        img: "https://aki-gm-resources-back.aki-game.net/notice/image/RhasUibVrDXaewvP.jpg",
        color: "#B19CA4",
        startDate: "2024-06-06 10:00",
        endDate: "2024-06-26 11:59",
    },
    {
        name: "Thawborn Renewal - Jinhsi Banner",
        img: "https://raw.githubusercontent.com/antisocial93/WuWa-base/main/jinhsiConvene.jpg",
        color: "#2B3C3E",
        startDate: "2024-06-28 12:00",
        endDate: "2024-07-22 09:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Absolute Pulsation - Jinhsi Weapon Banner",
        img: "https://raw.githubusercontent.com/antisocial93/WuWa-base/main/agesofharvestConvene.jpg",
        color: "#B3BBBE",
        startDate: "2024-06-28 12:00",
        endDate: "2024-07-22 09:59",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Stellar Plummage - Changli Banner",
        img: "https://snipboard.io/VlJ2EM.jpg",
        color: "#88302d",
        startDate: "2024-07-22 10:00",
        endDate: "2024-08-14 11:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Absolute Pulsation - Changli Weapon Banner",
        img: "https://snipboard.io/tsbezS.jpg",
        color: "#ee8548",
        startDate: "2024-07-22 10:00",
        endDate: "2024-08-14 11:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Chromatic Prose - Zhezhi Banner",
        img: "https://snipboard.io/xcDvKo.jpg",
        startDate: "2024-08-15 13:00",
        endDate: "2024-09-07 09:59",
        color: "#7cb3ba",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
      },
      {
        name: "Absolute Pulsation - Zhezhi Weapon Banner",
        img: "https://snipboard.io/LiUNfr.jpg",
        startDate: "2024-08-15 13:00",
        endDate: "2024-09-07 09:59",
        color: "#4fbdbe",
        isGlobal: true,
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
      },
      {
        name: "Celestial Revelation - Xiangli Yao Banner",
        img: "https://snipboard.io/6Ywh7F.jpg",
        startDate: "2024-09-07 10:00",
        endDate: "2024-09-28 11:59",
        color: "#5562cc",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
      },
      {
        name: "Absolute Pulsation - Xiangli Yao Weapon Banner",
        img: "https://snipboard.io/6zIkbw.jpg",
        startDate: "2024-09-07 10:00",
        endDate: "2024-09-28 11:59",
        color: "#483a74",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
      },
      {
        name: "Til the Sea Turns Clear - Shorekeeper Banner",
        img: "https://snipboard.io/emZLR4.jpg",
        description: "Featured 4* are; Taoqi, Yangyang, Chixia.",
        startDate: "2024-09-29 11:00",
        endDate: "2024-10-24 09:59",
        isGlobal: true,
        color: "#294156",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
      },
      {
        name: "Absolute Pulsation - Shorekeeper Weapon Banner",
        img: "https://snipboard.io/7WbTz0.jpg",
        description: "Featured 4* are; Endless Collapse, Discord, Comet Flare.",
        startDate: "2024-09-29 11:00",
        endDate: "2024-10-24 09:59",
        isGlobal: true,
        color: "#7871a5",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
      },
      {
        name: "Prevail The Lasting Night - Jiyan Rerun Banner",
        img: "https://snipboard.io/S5xARm.jpg",
        description: "Featured 4* are; Youhu, Sanhua, Mortefi.",
        startDate: "2024-10-24 10:00",
        endDate: "2024-11-13 11:59",
        color: "#54c1d6",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
      },
      {
        name: "Absolute Pulsation - Jiyan Weapon Banner",
        img: "https://snipboard.io/MugnOr.jpg",
        description:
          "Featured 4* are; Celestial Spiral, Variation, Helios Cleaver.",
        startDate: "2024-10-24 10:00",
        endDate: "2024-11-13 11:59",
        color: "#92875d",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
      },
      {
        name: "End of Lost Trail - Camellya Banner",
        img: "https://snipboard.io/4dcm9b.jpg",
        description: "Featured 4* are; Danjin, Yangyang, Aalto.",
        startDate: "2024-11-14 11:00",
        endDate: "2024-12-12 09:59",
        isGlobal: true,
        color: "#402821",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
      },
      {
        name: "Red Spring - Camellya Weapon Banner",
        img: "https://snipboard.io/U5wIMa.jpg",
        description:
          "Featured 4* are; Fusion Accretion, Commando of Conviction, Novaburst.",
        startDate: "2024-11-14 11:00",
        endDate: "2024-12-12 09:59",
        isGlobal: true,
        color: "#a84955",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
      },
      {
        name: "Featured Resonator - Yinlin & Xiangli Yao Rerun Banners",
        img: "https://snipboard.io/uyqe72.jpg",
        description: "Featured 4* are; Lumi, Baizhi, Yuanwu.",
        startDate: "2024-12-12 10:00",
        endDate: "2025-01-01 11:59",
        color: "#653e91",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
      },
      {
        name: "Featured Weapon - Yinlin & Xiangli Yao Rerun Weapon Banners",
        img: "https://snipboard.io/XZOYjk.jpg",
        description:
          "Featured 4* are; Waning Redshift, Jinzhou Keeper, Hollow Mirage.",
        startDate: "2024-12-12 10:00",
        endDate: "2025-01-01 11:59",
        color: "#272540",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
      },
];

export const BANNERS = convertDatesToServerTime(ALL_BANNERS);
