import { convertDatesToServerTime } from "@/shared/helpers/time";

const TOWER_OF_ADVERSITY = [
    {
        name: "Tower of Adversity: Hazard Zone",
        img: "https://raw.githubusercontent.com/antisocial93/WuWa-base/main/hazardzoneicon.jpg",
        color: "#1F275E",
        description: ``,
        startDate: "2024-06-23 04:00",
        endDate: "2024-07-07 03:59",
    },
    {
        name: "Tower of Adversity: Hazard Zone",
        img: "https://raw.githubusercontent.com/antisocial93/WuWa-base/main/hazardzoneicon.jpg",
        color: "#1F275E",
        description: ``,
        startDate: "2024-07-07 04:00",
        endDate: "2024-07-21 03:59",
    },
    {
        name: "Tower of Adversity: Hazard Zone",
        img: "https://raw.githubusercontent.com/antisocial93/WuWa-base/main/hazardzoneicon.jpg",
        color: "#1F275E",
        description: ``,
        startDate: "2024-07-21 04:00",
        endDate: "2024-08-05 03:59",
    },
    {
        name: "Tower of Adversity",
        img: "https://raw.githubusercontent.com/antisocial93/WuWa-base/main/hazardzoneicon.jpg",
        color: "#1F275E",
        description: ``,
        startDate: "2024-08-05 04:00",
        endDate: "2024-08-19 03:59",
    },
    {
        name: "Tower of Adversity: Hazard Revisited",
        img: "https://snipboard.io/NnA3YO.jpg",
        startDate: "2024-09-16 04:00",
        endDate: "2024-09-30 04:00",
        color: "#18235f",
    },
    {
        name: "Tower of Adversity: Hazard Revisited",
        img: "https://snipboard.io/NnA3YO.jpg",
        startDate: "2024-10-28 04:00",
        endDate: "2024-11-11 04:00",
        color: "#18235f",
        reliability: "Official",
    },
    {
        name: "Tower of Adversity: Hazard Revisited",
        img: "https://snipboard.io/NnA3YO.jpg",
        startDate: "2024-11-11 04:00",
        endDate: "2024-11-25 04:00",
        color: "#18235f",
        reliability: "Official",
    },
    {
        name: "Tower of Adversity: Hazard Revisited",
        img: "https://snipboard.io/NnA3YO.jpg",
        startDate: "2024-11-25 04:00",
        endDate: "2024-12-09 04:00",
        color: "#18235f",
        reliability: "Official",
    },
];

const DEPTHS_OF_ILLUSIVE_REALM = [
    {
        name: "Depths of Illusive Realm",
        img: "https://snipboard.io/ZU4bEz.jpg",
        color: "#7E88B0",
        description: ``,
        startDate: "2024-05-22 12:00",
        endDate: "2024-06-27 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Depths of Illusive Realm: Dreams Ablaze in Darkness",
        img: "https://snipboard.io/ZU4bEz.jpg",
        color: "#9a4431",
        description: `The New Season "Dreams Ablaze in Darkness" opens! New mechanics such as Tokens, Symphony Rank, and different Memetic Tuning are available for you to create your own powerful build. Main rewards are; 1000x Astrite, 1x Malleable Elite Class Echo I, 1x Malleable Elite Class Echo II, Premium Tuners, Crystal Solvents.`,
        startDate: "2024-07-04 10:00",
        endDate: "2024-08-05 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Depths of Illusive Realm: Carnival in Slumberland",
        img: "https://snipboard.io/LG7Hsb.jpg",
        description: `New Content "Carnival in Slumberland" Open! Phantom Echo: Dreamless and new Metaphors will be available for you to select. Rewards; 1000*Astrite, Phantom: Dreamless, Malleable Elite Class Echo I, Malleable Elite Class Echo II, Premium Sealed Tubes.`,
        startDate: "2024-08-22 10:00",
        endDate: "2024-09-23 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        color: "#b66188",
    },
    {
        name: "Depths of Illusive Realm - Phantasm Amass",
        img: "https://snipboard.io/2EorCx.jpg",
        description: `New Content "Phantasm Amass" now available! Step into surreal, ever-shifting dreamscapes, where new maps await exploration and formidable enemies lurk in the shadows, and uncover the secrets that lie within! Rewards; 1000*Astrite, Phantom: Inferno Rider, Malleable Elite Class Echoes, Premium Sealed Tube, Weapon Projections.`,
        startDate: "2024-11-14 11:00",
        endDate: "2025-01-01 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        color: "#545f5a",
    },
];

const PIONEER_PODCAST = [
    {
        name: "Pioneer Podcast",
        img: "https://snipboard.io/dBPpt2.jpg",
        color: "#e4c190",
        description: `You can complete tasks in Pioneer Podcast and accumulate Podcast EXP. Level up your Podcast to get rich rewards. Unlock "Insider Channel" or "Connoisseur Channel" and level up your Podcast to win extra rewards including Astrite*600, a 4-star Golden Eternal Series Weapon of Choice, and Radiant Tide!`,
        startDate: "2024-05-22 12:00",
        endDate: "2024-06-27 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Pioneer Podcast",
        img: "https://snipboard.io/dBPpt2.jpg",
        color: "#e4c190",
        description: `You can complete tasks in Pioneer Podcast and accumulate Podcast EXP. Level up your Podcast to get rich rewards. Unlock "Insider Channel" or "Connoisseur Channel" and level up your Podcast to win extra rewards including Astrite*600, a 4-star Golden Eternal Series Weapon of Choice, and Radiant Tide!`,
        startDate: "2024-06-28 12:00",
        endDate: "2024-08-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/975",
    },
    {
        name: "Pioneer Podcast",
        img: "https://snipboard.io/1EkOtV.jpg",
        description: `You can complete tasks in Pioneer Podcast and accumulate Podcast EXP. Level up your Podcast to get rich rewards. Unlock "Insider Channel" or "Connoisseur Channel" and level up your Podcast to win extra rewards including Astrite*680, a 4-star Golden Eternal Series Weapon of Choice, Radiant Tide, and more! Unlocking "Connoisseur Channel" grants an instant advance of Podcast level by 10, with the period-limited Sigil "Moonlit Haven", Lustrous Tide*3, and Gilded Ginkgo (can be used to improve the Syntonization Rank of a 4-star Golden Eternal Series Weapon).`,
        startDate: "2024-08-15 13:00",
        endDate: "2024-09-28 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1147",
        color: "#594842",
    },
    {
        name: "Pioneer Podcast",
        img: "https://snipboard.io/fiqQbc.jpg",
        description: `You can complete tasks in Pioneer Podcast and accumulate Podcast EXP. Level up your Podcast to get rich rewards. Unlock "Insider Channel" or "Connoisseur Channel" and level up your Podcast to win extra rewards including Astrite*680, a 4-star Golden Eternal Series Weapon of Choice, Radiant Tide, and more! Unlocking "Connoisseur Channel" grants an instant advance of Podcast level by 10, with the period-limited Sigil "Sound of Tides", Lustrous Tide*3, and Gilded Ginkgo (can be used to improve the Syntonization Rank of a 4-star Golden Eternal Series Weapon).`,
        startDate: "2024-09-29 11:00",
        endDate: "2024-11-13 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1408",
    },
    {
        name: "Pioneer Podcast",
        img: "https://snipboard.io/2Z7Ncr.jpg",
        description: `You can complete tasks in Pioneer Podcast and accumulate Podcast EXP. Level up your Podcast to get rich rewards. Unlock "Insider Channel" or "Connoisseur Channel" and level up your Podcast to win extra rewards including Astrite*680, a 4-star Golden Eternal Series Weapon of Choice, Radiant Tide, and more! Unlocking "Connoisseur Channel" grants an instant advance of Podcast level by 10, with the period-limited Sigil "Sound of Tides", Lustrous Tide*3, and Gilded Ginkgo (can be used to improve the Syntonization Rank of a 4-star Golden Eternal Series Weapon).`,
        startDate: "2024-11-14 11:00",
        endDate: "2025-01-01 03:59",
        url: "https://wutheringwaves.kurogames.com/en/main/news/detail/1607",
        reliability: "Official",
        color: "#645676",
      },
];

export const COMMONS = [
    convertDatesToServerTime(TOWER_OF_ADVERSITY),
    convertDatesToServerTime(DEPTHS_OF_ILLUSIVE_REALM),
    convertDatesToServerTime(PIONEER_PODCAST),
];
