import { Resonator } from ".";
import { RESONATOR_ICON_PATH, RESONATOR_IMAGE_PATH } from "../helpers/paths";
import { WEAPON_TYPE_NAMES } from "../weapons/types";
import { ELEMENT_NAMES } from "./elements";

const QUALITY = 5;

export const FIVE_STAR_RESONATOR_NAMES = {
  BRANT: "Brant",
  CALCHARO: "Calcharo",
  CAMELLYA: "Camellya",
  CANTARELLA: "Cantarella",
  CARLOTTA: "Carlotta",
  CHANGLI: "Changli",
  ENCORE: "Encore",
  JIANXIN: "Jianxin",
  JINHSI: "Jinhsi",
  JIYAN: "Jiyan",
  LINGYANG: "Lingyang",
  PHOEBE: "Phoebe",
  ROCCIA: "Roccia",
  ROVER_HAVOC: "Rover (Havoc)",
  ROVER_SPECTRO: "Rover (Spectro)",
  SHOREKEEPER: "Shorekeeper",
  VERINA: "Verina",
  XIANGLI_YAO: "Xiangli Yao",
  YINLIN: "Yinlin",
  ZHEZHI: "Zhezhi",
} as const;

export const FIVE_STAR_RESONATORS = {
  [FIVE_STAR_RESONATOR_NAMES.BRANT]: {
    element: ELEMENT_NAMES.FUSION,
    weapon: WEAPON_TYPE_NAMES.SWORD,
    image: `${RESONATOR_IMAGE_PATH}/brant.webp`,
    icon: `${RESONATOR_ICON_PATH}/brant.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.CALCHARO]: {
    element: ELEMENT_NAMES.ELECTRO,
    weapon: WEAPON_TYPE_NAMES.BROADBLADE,
    image: `${RESONATOR_IMAGE_PATH}/calcharo.webp`,
    icon: `${RESONATOR_ICON_PATH}/calcharo.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.CAMELLYA]: {
    element: ELEMENT_NAMES.HAVOC,
    weapon: WEAPON_TYPE_NAMES.SWORD,
    image: `${RESONATOR_IMAGE_PATH}/camellya.webp`,
    icon: `${RESONATOR_ICON_PATH}/camellya.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.CANTARELLA]: {
    element: ELEMENT_NAMES.HAVOC,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/cantarella.webp`,
    icon: `${RESONATOR_ICON_PATH}/cantarella.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.CARLOTTA]: {
    element: ELEMENT_NAMES.GLACIO,
    weapon: WEAPON_TYPE_NAMES.PISTOLS,
    image: `${RESONATOR_IMAGE_PATH}/carlotta.webp`,
    icon: `${RESONATOR_ICON_PATH}/carlotta.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.CHANGLI]: {
    element: ELEMENT_NAMES.FUSION,
    weapon: WEAPON_TYPE_NAMES.SWORD,
    image: `${RESONATOR_IMAGE_PATH}/changli.webp`,
    icon: `${RESONATOR_ICON_PATH}/changli.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.ENCORE]: {
    element: ELEMENT_NAMES.FUSION,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/encore.webp`,
    icon: `${RESONATOR_ICON_PATH}/encore.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.JIANXIN]: {
    element: ELEMENT_NAMES.AERO,
    weapon: WEAPON_TYPE_NAMES.GAUNTLETS,
    image: `${RESONATOR_IMAGE_PATH}/jianxin.webp`,
    icon: `${RESONATOR_ICON_PATH}/jianxin.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.JINHSI]: {
    element: ELEMENT_NAMES.SPECTRO,
    weapon: WEAPON_TYPE_NAMES.BROADBLADE,
    image: `${RESONATOR_IMAGE_PATH}/jinhsi.webp`,
    icon: `${RESONATOR_ICON_PATH}/jinhsi.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.JIYAN]: {
    element: ELEMENT_NAMES.AERO,
    weapon: WEAPON_TYPE_NAMES.BROADBLADE,
    image: `${RESONATOR_IMAGE_PATH}/jiyan.webp`,
    icon: `${RESONATOR_ICON_PATH}/jiyan.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.LINGYANG]: {
    element: ELEMENT_NAMES.GLACIO,
    weapon: WEAPON_TYPE_NAMES.GAUNTLETS,
    image: `${RESONATOR_IMAGE_PATH}/lingyang.webp`,
    icon: `${RESONATOR_ICON_PATH}/lingyang.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.PHOEBE]: {
    element: ELEMENT_NAMES.SPECTRO,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/phoebe.webp`,
    icon: `${RESONATOR_ICON_PATH}/phoebe.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.ROCCIA]: {
    element: ELEMENT_NAMES.HAVOC,
    weapon: WEAPON_TYPE_NAMES.GAUNTLETS,
    image: `${RESONATOR_IMAGE_PATH}/roccia.webp`,
    icon: `${RESONATOR_ICON_PATH}/roccia.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.ROVER_HAVOC]: {
    element: ELEMENT_NAMES.HAVOC,
    weapon: WEAPON_TYPE_NAMES.SWORD,
    image: `${RESONATOR_IMAGE_PATH}/rover.webp`,
    icon: `${RESONATOR_ICON_PATH}/rover.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.ROVER_SPECTRO]: {
    element: ELEMENT_NAMES.SPECTRO,
    weapon: WEAPON_TYPE_NAMES.SWORD,
    image: `${RESONATOR_IMAGE_PATH}/rover.webp`,
    icon: `${RESONATOR_ICON_PATH}/rover.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.SHOREKEEPER]: {
    element: ELEMENT_NAMES.SPECTRO,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/shorekeeper.webp`,
    icon: `${RESONATOR_ICON_PATH}/shorekeeper.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.VERINA]: {
    element: ELEMENT_NAMES.SPECTRO,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/verina.webp`,
    icon: `${RESONATOR_ICON_PATH}/verina.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.XIANGLI_YAO]: {
    element: ELEMENT_NAMES.ELECTRO,
    weapon: WEAPON_TYPE_NAMES.GAUNTLETS,
    image: `${RESONATOR_IMAGE_PATH}/xiangli_yao.webp`,
    icon: `${RESONATOR_ICON_PATH}/xiangli_yao.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.YINLIN]: {
    element: ELEMENT_NAMES.ELECTRO,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/yinlin.webp`,
    icon: `${RESONATOR_ICON_PATH}/yinlin.webp`,
    quality: QUALITY,
  },
  [FIVE_STAR_RESONATOR_NAMES.ZHEZHI]: {
    element: ELEMENT_NAMES.GLACIO,
    weapon: WEAPON_TYPE_NAMES.RECTIFIER,
    image: `${RESONATOR_IMAGE_PATH}/zhezhi.webp`,
    icon: `${RESONATOR_ICON_PATH}/zhezhi.webp`,
    quality: QUALITY,
  },
} as Record<string, Resonator>;
